PROJECT=Obbligato
PROJECT_NAME=Obbligato
PROJECT_VERSION?=20130106
PROJECT_EMAIL=jeffk@jdkoftinoff.com
PROJECT_LICENSE=ISC
PROJECT_MAINTAINER=jeffk@jdkoftinoff.com
PROJECT_COPYRIGHT=Copyright 2013
PROJECT_DESCRIPTION=
PROJECT_WEBSITE=https://obbligato.statusbar.com/
PROJECT_IDENTIFIER=org.statusbar.obbligato
TOP_LIB_DIRS+=.
CONFIG_TOOLS+=
PKGCONFIG_PACKAGES+=
TEST_OUT_SUFFIX=txt

CONFIG_TOOLS=

